---
abstract: "automatically filter function's return value"
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  ExtUtils::CBuilder: 0.15
  Module::Build: 0
  Sub::Mutate: 0.001
  Test::More: 0
  perl: 5.006001
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.006001
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Filter
provides:
  Sub::Filter:
    file: lib/Sub/Filter.pm
    version: 0.001
requires:
  Attribute::Lexical: 0.002
  Carp: 0
  Sub::Mutate: 0.001
  XSLoader: 0
  perl: 5.006001
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
